
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      hibernate.format_sql: true
